### ISSUE TITLE
Installation Failed: No System Restore sequence number

### ISSUE THREAD

**Issue by aqeel1** [eapowertools/qs-telemetry-dashboard#83]
[MSIfb30d.LOG](https://github.com/eapowertools/qs-telemetry-dashboard/files/3741886/MSIfb30d.LOG)

Appreciate your help here. thanks

**Comment by levi-turner** [comment]
Given the trace of:
```
SFXCA: Extracting custom action to temporary directory: ...
SFXCA: Binding to CLR version v4.0.30319
Calling custom action CustomActions!CustomActions.CustomActions.IsRepositoryRunning
Making a request to 'https://server.company.com:4242
Exception thrown by custom action:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Qlik\Sense\Repository\Exported Certificates\.Local Certificates\client.pem' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at CustomActions.CustomActions.SetTLSandGetCertificate()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at CustomActions.CustomActions.MakeQrsRequest(String path, HttpMethod method, HTTPContentType contentType, Byte body)
   at CustomActions.CustomActions.IsRepositoryRunning(Session session)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object parameters, Object arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object parameters, CultureInfo culture)
   at Microsoft.Deployment.WindowsInstaller.CustomActionProxy.InvokeCustomAction(Int32 sessionHandle, String entryPoint, IntPtr remotingDelegatePtr)
CustomAction IsRepositoryRunningAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 21:04:29: InstallFinalize. Return value 3.
```

Please verify that the permission issue described [here](https://youtu.be/EPLl1BODwH4?t=59) is not at play.

**Comment by aqeel1** [comment]
Hi Levi

Thank you so much۔ Yes you are right۔ it was the permissions issue۔ I tried
installing with a service acct user with admin rights, it installed
successfully.

I may have overridden inherent security permissions on the RootShare folder
by selecting the option to "Replace all child permissions.." when trying to
grant my userId full access. Now I cannot access at all. Hope it doesn't
carry any damaging consequences?

**Comment by aqeel1** [comment]
I just attempted reloading Telemetry tasks, (2) failed with this error

2019-10-18 14:17:01      Error: Cannot open file:
'lib://TelemetryMetadata/apps.csv' (Native Path: ***
2019-10-18 14:17:01      System error: ***)
2019-10-18 14:17:01      Execution Failed

**Comment by jparis** [comment]
Sounds like whatever permissions you changed on the folder have impacted the telemetry task. It seemingly can't access the share.

**Comment by aqeel1** [comment]
Thanks. Reverting back the permissions settings helped. I had to uninstall
and reinstall. Now the app works fine!! This is a great product.
